### PR TITLE
Gregory bretall lps 69305

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @gregory-bretall

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by gregory-bretall** [comment]
I looked more into this and it seems that performing += 0 isn't an allowed operation on offsetWidth, so instead I'll have to change to a dead function call (in this case .toFixed() as toString and valueOf get removed by the minifier).  I can resend the pull request with this update.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
@gregory-bretall thanks for the update. Please go ahead and resend the fix whenever it's ready.

**Comment by gregory-bretall** [comment]
Just as a note, I resent the pull request to Sam with the change to the behavior, so we can close this PR.

**Pull request closed without merging**
