### PR TITLE
LPS-67718

### PR DESCRIPTION
**Pull request by blzaugg**
Reviewed UI behavior and forwarded. No code review.

> This is a fix for [LPS-67718](https://issues.liferay.com/browse/LPS-67718)
> 
> The issue is that when we select a parent page, and deselect some its children pages, after click on "load more results"(IO request), the deselected nodes are selected automatically.
> 
> The reason is that when IO completes, we will call ``_updateCheckedNodes``, which will force all chidlren node to be the same state with their parent node.
> 
> To solve this issue, updateCheckedNodes requires to be able to resolve two basic scenarios:
> 
> 1. Explicit updateCheckedNodes. When click/unclick on a parent node, we expect all its children nodes to be selected/unselected automatically. In this case, we force all children node having consistent states with their parents.
> 
> 2. Implict updateCheckedNodes. When click on load more results or detect childrenNodeChanges, we expect the all local changed children nodes remaining their current status and new loaded children nodes respect their original states. In this case, we allow children nodes and their parents having different states.
> 
> Let know if you have any concerns about the fix.
> 
> /cc @daledotshan @jonmak08
> 
> Thanks
> John.

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hoping to be able to review this tomorrow.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Will have an update on this tomorrow.

**Comment by daledotshan** [comment]
Hey Dustion,
Could you help to review this ticket, it is for a customer?
Thanks,
Dale

**Comment by dustinryerson** [comment]
Reviewed and pushed to Jon Mak: https://github.com/jonmak08/liferay-portal/pull/1611

**Comment by dustinryerson** [comment]
Resent: https://github.com/dustinryerson/liferay-portal/pull/77

**Pull request closed without merging**
