### PR TITLE
[Technical Support] LPS-70791 StripFilter.java missing named constant

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

First of all, I'd like to say that the original related issue is LPS-70588 in that we have a css parsing issue. During the test of that issue Omar realized that issue is not reproducible on Master.
Why?
The answer is in this issue. Because custom css, it is given through portlet look and feel, is never filtered by StripFilter on Master and 7.0.x.

The reason of it that StripFilter uses " _MARKER_STYLE_OPEN = "style type=\"text/css\">".toCharArray()"
constant to find starter tag element of a style tag.

The problem is that since we use SinglePageApplication our generated style element will contain a "data-senna-track="temporary"" or "data-senna-track="permanent"" strings. We don't have markers which would match these kind of style elements.

Omar in his solution added two new markers to ensure a good matching with style element.

I hope I could clarify a bit this issue and it's solution.

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @dustinryerson, this has been lingering on for a while... is there anything we can do to get it going?

Thanks!

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
@jbalsas I can get it moving again.

@omarzzn3 does https://issues.liferay.com/browse/LPS-70791 have any steps to reproduce since it's categorized as a `Bug` ticket? Will you please update the LPS with those details? Once you do that I'll forward the pull.

Thanks!

**Comment by omarzzn3** [comment]
Hi Dustin, 

Thank you for reviewing this pull.

To answer your question, this is not really a bug but as explained by Zsolt in the beginning, I  modified the StripFilter as a major step in fixing the original bug which is [LPS-70588](https://issues.liferay.com/browse/LPS-70588).
But in order to follow the policy, I had to create a separate LPS for this issue since there is another step to take in order to fix the original issue which is to update the yui-compressor.jar file in the source that will be done in the original LPS.
We need to update it because the reported bug is fixed in the newer version of the yui-compressor.jar file.

Please let me know if I have to fix or do something regarding this and feel free ask me any further questions.

Best regards,
Omar

**Pull request closed without merging**
