### PR TITLE
LPS-74548 Disable reordering while on mobile devices as scrolling up …

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Dustin,

Jonathan said to go ahead and send this directly to you since it deals with UI/UX

This fix disables the page reordering in the product menu while browsing on mobile devices. Scrolling up and down on a page while reordering is enabled becomes difficult without reordering the nodes.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
@dustinryerson sorry about that Dustin, I've done the source format now.

**Comment by SamZiemer** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1110. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/18db9492daf1~1...18db9492daf1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
