### PR TITLE
LPS-54160

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
when the user is a guest this fix basically reverts the behavior to what it was before LPS-49793 was committed

**Comment by BryanEngler** [comment]
if you havent looked at this yet you could probably forward it to mccann now that hes back if youre busy with other stuff

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/630. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
