### PR TITLE
LPS-54080 document library exception handling

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
This is low priority but is likely to have rebasing issues.

**Comment by Preston-Crary** [comment]
Doesn't look related.

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Didn't have time to get to this one today, but should get to it soon.

**Comment by dustinryerson** [comment]
Hey @Preston-Crary,

I didn't have a chance to get to this one until today, but you were right and there are now rebase errors, but I don't have time to resolve them. Can you resolve them and resend this to Jonathan?

Thanks!

**Comment by Preston-Crary** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/752

**Pull request closed without merging**
