### PR TITLE
LPS-72179 (Option B) Placeholder in inputDate taglib is not internacionalized

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey @dustinryerson, This PR solved the case you indicated in [this comment](https://github.com/dustinryerson/liferay-portal/pull/135#discussion_r114382082). I made it a new PR to try to keep as clean as possible. Thanks

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:reopen

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/385. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/1577658ecc16~1...1577658ecc16) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
