### PR TITLE
LPS-54744 rebase

### PR DESCRIPTION
**Pull request by arbetts**
https://github.com/jonathanmccann/liferay-portal/pull/786

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
i'm not sure what these test failures are, but i don't think my changes are responsible.

not sure how background task changes could effect sharding
[Bogeyman] high disk watermark [90%] exceeded on [ufT533xoT76P9apxQkWQ-w][Bogeyman] free: 4.1gb[8.4%], shards will be relocated away from this node

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1123. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
