### PR TITLE
LPS-73338 Adding attribute disableCheckbox into input-date taglib

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-73338

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @dustinryerson,
I didn't change this code so I think this testing is not working fine.

**Comment by JosemariaMunoz** [comment]
Hey @dustinryerson!
Could you please tell me something about this solution? Sorry for ask, but there is a customer waiting for this solution for a long time... Thanks a lot!

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by almonwork** [comment]
Hi @dustinryerson ,

Any update on this?

Regards
  Alberto

**Comment by JosemariaMunoz** [comment]
Great! Thank you very much @dustinryerson !

**Comment by almonwork** [comment]
Thanks @dustinryerson

**Pull request closed without merging**
