### PR TITLE
[TECHNICAL-SUPPORT] LPS-65275

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hi @dustinryerson,

It said it failed the Source Formatter test both here and on the [pull request](https://github.com/SamZiemer/liferay-portal/pull/36) I initially sent @SamZiemer. However, when I ran the ant format-source command on my repo, it did not modify or otherwise mention any of the files modified in this pull request (it did modify a huge amount of other files, however). I'm not really sure what to make of this.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/199. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/50ce87a~1...50ce87a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
