### PR TITLE
LPS-67448

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
I have not reviewed this. I'm on another priority project.

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Should have time to finish this up tomorrow.

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/1026. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
