### PR TITLE
Lps 64632

### PR DESCRIPTION
**Pull request by Alec-Shay**
Changed the commits a bit for clarity and added generated language keys.

This change is re-submitted, as previously it was changed to use "your-password-has-been-sent-to-x" (x being the email address of the user) for the success message. However, since this may inadvertently reveal the user's email address if the authentication is not already by email address, I think the best alternative would be to change it in favor of a new, more generic message.

I suppose if we do not want to make a new language key, the even more generic "The request was successful" could also be appropriate, but I think a new key makes the most sense.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/979. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Great work @Alec-Shay!

**Comment by Alec-Shay** [comment]
Thanks, and thank you too for all the help @dustinryerson!

**Pull request closed without merging**
