### PR TITLE
LPS-55681 Add better exception messages for Login

### PR DESCRIPTION
**Pull request by eric-chi**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hi @eric-chi ,

One of the requirements for sending pull requests is to have your association with the Liferay organization on GitHub public so that our automated tests can run (see https://github.com/dustinryerson/liferay-portal/pull/31). When you have the time, would you mind setting your membership to public? I'm providing a wiki link below with instructions from GitHub.

Wiki link: https://help.github.com/articles/publicizing-or-concealing-organization-membership/

I'm not supposed to push any pull requests through unless they pass these tests, so as soon as you're able to complete the steps above, I can take care of this pull.

Please let me know if you have any questions.

Thanks!

**Comment by eric-chi** [comment]
Hey @dustinryerson ,

I finished the requirement for switching my association with Liferay to public. Thanks for the heads up!

**Comment by dustinryerson** [comment]
Awesome, thanks Eric!

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/mikakoivisto/liferay-portal/pull/77. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
