### PR TITLE
LPS-69001

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3600. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by SamZiemer** [comment]
Hi @dustinryerson,
This ticket was just from the LPS assign queue, so there was not an LPP involved.

**Comment by dustinryerson** [comment]
Got it, thanks @SamZiemer!

**Pull request closed without merging**
