### PR TITLE
[TECHNICAL SUPPORT] LPS-67298 Using adjustedDate in validation methods

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

Today morning I noticed that a ticket (LPS-67298), which I fixed 3 weeks ago, was failed on QA tests and that QA engineer opened a new ticket (LPS-67866) for it. I checked again my sent code changes and I found that I missed using the made new "adjustedToday" object in validation methods.
Maybe I did it because I firstly made that fix on ee-6.2.x and nobody checks the correctly of that fix.

LPS-67298 would be complete if we add this change as well. Can we add this change to LPS-67298  or we should fix LPS-67866?

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @zsagia, sorry for the delay on this. I'm hoping to have some time to work on it tomorrow.

**Comment by dustinryerson** [comment]
Will get to this next Monday.

**Comment by dustinryerson** [comment]
Hey @zsagia, I think we should go ahead and use LPS-67866 for this fix since LPS-67298 is already closed. I think that's how Brian wants us to use the JIRA tickets. Would you mind resending with everything referencing LPS-67866? Sorry for the trouble. Thank for the details you provided!

**Comment by zsagia** [comment]
Hi Dustin,

Ok, I'm doing it.

Thanks a lot,


Zsolt Szabo a.k.a. Zsaga

Engineer, Technical Support

Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary

**Comment by zsagia** [comment]
I'm sending a newer and close it.

**Pull request closed without merging**
