### PR TITLE
LPS-69640 Depending on locale add 12 hours to hourOfDay when creating Calendar object

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hoping to be able to review this tomorrow.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hey @rodrigopaulino, can you provide some clarification for this bug?

The issue seems to be that when a user goes to schedule a new publication, the actual time is not filled in the field by default, but rather some time after the actual time (8 hrs. in my testing). I think I may be misunderstanding the point of this bug. What is the reasoning for wanting the actual time to be the default value for the field rather than some time in the future, say +8 hours from actual time?

**Comment by rodrigopaulino** [comment]
Hi @dustinryerson, I sure can.

Actually, the bug depends on locales that uses a time pattern of 24 hours instead of AM-PM. Let's say, if you choose Brazilian Portuguese as language and the actual time is past noon, the default time set in this field is the actual time +12h rather than just have the actual time as it is when using some other locales.
Hope that answer clarifies your question.

Regards.

**Comment by dustinryerson** [comment]
Hey @rodrigopaulino, my apologies for the long delay for this review, I've been caught up with some other work. This review will be at the top of my priorities when we return from Christmas Holiday next Tuesday.

**Comment by dustinryerson** [comment]
Hey @rodrigopaulino I ran out of time to get to this today, but it will be the first thing I work on tomorrow. Sorry again for the delay.

**Comment by rodrigopaulino** [comment]
No problem, @dustinryerson!
Thanks for the update. 👍

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1598. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
