### PR TITLE
[Technical-Support] LPS-72118

### PR DESCRIPTION
**Pull request by yuhai**
cc @dacousalr,

Hi Dustin,

Based on @dacousalr guide, I revert LPS-71557 and LPS-71271, his fix will cover the kind of issue. And I have tested and it works for me.

By the way, the revert doesn't include three commit:
1.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/bae81a4d2d214bcd36d4d951ec70a223d108ad1f
2.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/a128c398e1efd67ba7095bce5e99f67f7b58f6f7
3.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/2ece88e0cceee98c506a3057482073e932009442

Because jsp doesn't use previous add linkData property. file_entry_history_action.jsp fix has been remove from LPS-71635

If you have further concerns, please kindly let me know.

Best Regards,
Hai

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Pull request closed without merging**
