### PR TITLE
[Technical Support] LPS-72761 Copying css code for ".ae-sr-only" selector from alloy-editor

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

Please, read my description on the related LPS ticket. I tried to describe what is the customer's and the original issue.

My sent solution can solve this issue only but, I think, we need to find a common solution for this kind of problems.

Thanks in advance for your review and the best,
 Zsaga

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by zsagia** [comment]
ci:retest

**Comment by zsagia** [comment]
ci:retest

**Comment by zsagia** [comment]
Hi Dustin,

This is just a reminder. :)

**Comment by dustinryerson** [comment]
Thanks for the reminder @zsagia :)

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/391. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/adc135055c79~1...adc135055c79) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
