### PR TITLE
LPS-59490

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
Dustin, could you review this Java code. See previous PR comment: https://github.com/blzaugg/liferay-portal/pull/153#commitcomment-13965269

**Comment by blzaugg** [comment]
If all is good, you can send it up your normal review chain.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/859. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
