### PR TITLE
LPS-73370

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @dustinryerson. This issue was reported by a customer. A short reasoning for the pull request is the following. When no value of id is set for the taglib, it takes the value of name in InputLocalizedTag.java and it is used with getAUICompatibleId(id) in input_localized/init.jsp. The value of name must be applied the same method, getAUICompatibleId, when it is used in the definition of fieldName in init.jsp. Both id and fieldName will be used later in input_localized/page.jsp. Tell me if you have any questions. Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by ricardocousolr** [comment]
ci:reopen

**Comment by ricardocousolr** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Thanks, Dustin!

**Pull request closed without merging**
