### PR TITLE
LPS-53375

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/dustinryerson/liferay-portal/pull/16" target="_blank">ReviewNinja

**Comment by jonathanmccann** [comment]
Hey Dustin,

I'm sending this back to you to make sure this makes sense to do and that it still works. I basically just put the logic underneath the if statement to reduce the need to iterate over the articles twice. Another thought I had was to change the SQL itself to use DISTINCT that was we would not need to check if the article is the latest version or keep track of which articles we've already sent notifications for.

Let me know if you have any questions.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/597. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
