### PR TITLE
LPS-66646 Same role can be selected multiple time while editing any user.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Dustin 

This is a fix for LPS-66646.

Please refer to https://github.com/zxdgoal/liferay-portal/pull/15.

Let me know if you have any questions.

Thanks
John

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hoping to be able to review this tomorrow.

**Comment by dustinryerson** [comment]
Still wasn't able to get to this one today, but I will review it tomorrow for sure.

**Comment by zxdgoal** [comment]
Thank you, Dustin.

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Forwarded to Jon: https://github.com/jonmak08/liferay-portal/pull/1615

**Pull request closed without merging**
