### PR TITLE
LPS-65448

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/578. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
