### PR TITLE
LPS-57753 ensure that custom color picker is not displayed underneath…

### PR DESCRIPTION
**Pull request by arbetts**
… look and feel modal

### CODE REVIEW

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hey @arbetts,

Did you test your code in master? When I tested it did not resolve the issue.

Please revise and resend.

**Comment by arbetts** [comment]
I was unable to get master to work at all on friday.

i'll revise and resend,
thanks

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/jonmak08/liferay-portal/pull/1317. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
