### PR TITLE
LPS-71041

### PR DESCRIPTION
**Pull request by NolanChan**
Parallel change to `simple_menu.js` from LPS-64945

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:reopen

**Comment by NolanChan** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/360. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/cd2d52a~1...cd2d52a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
