### PR TITLE
[TECHNICAL SUPPORT] LPS-68593 Can't specify link to open in new tab in creole mode when editing wiki articles

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

Because version 1.3.0 of alloy-editor has committed I could start to fix this issue.
My addition code contains a button config for "linkEdit" component for alloy-editor. I placed it in the AlloyEditorCreoleConfigContributor class because creole standard doesn't support "target" attribute on a link element.

Don't forget that I had another related pull-request for alloy-editor which was fixed two month ago(LPS-68581).

Please let me know if you would have any question.

Thanks,
 Zsaga

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hey @zsagia, my apologies for the long delay for this review, I've been caught up with some other work. This review will be at the top of my priorities when we return from Christmas Holiday next Tuesday.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
@zsagia, quick question about this fix. During my testing, I found that when I was _creating_ a link, the target button is hidden, which is what is expected after your fix is applied. However, I found that after the link was created, if I _edit_ the link by clicking it, the AlloyEditor link editor opens again and at this time the target button is visible. Is this intended? Based on the details you provided on the fix, wouldn't we want to hide the target button when creating _and_ editing links in Creole mode?

**Comment by zsagia** [comment]
Hi @dustinryerson,

Your use case and test results are valid. Sorry about I didn't take a deeper test on it.
I debugged alloy-editor behavior and realized that editor uses a totally different element(ButtonLinkTargetEdit) when you click on a link in edit mode. (I made a change on ButtonTargetLink).
A ButtonLinkTargetEdit instance will be instantiated in every time when you edit a link. My question is Why?? Why does not editor check a Boolean value to decide what kind of element will be shown?

Summarizing the previous: it seems this is another alloy-editor issue and to fix it we need analyze this logic again.

What is your opinion? Maybe I need to open a new ticket and ask Iliyan about it?

Thanks,
 Zsaga

**Comment by dustinryerson** [comment]
Hey @zsagia I think your idea of opening a ticket and discussing this with Iliyan is the best way forward. Please go ahead and proceed with that.

Thanks!

**Pull request closed without merging**
