### PR TITLE
[Technical Support] LPS-70121 Creole Wiki shows options to resize images

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

We have a new configuration issue for Creole mode. Please read lps content.

Thanks

### CODE REVIEW

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey guys, I haven't reviewed this in depth, but this seems to be touching the default alloyeditor configuration instead of using the creole one or a specific wiki `editorconfigcontributor` to remove whatever plugins are not needed.

**Comment by zsagia** [comment]
Hi Guys,

I'm closing this pull because we are going to make a better solution.

**Comment by dustinryerson** [comment]
Forwarded to Sergio, Wiki component lead: https://github.com/sergiogonzalez/liferay-portal/pull/3758

**Pull request closed without merging**
