### PR TITLE
LPS-64630 Keep using the repositoryId parameter. From an architectural point of view this should be the repositoryId. This will help us when we want to support different repositories with workflow.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by BryanEngler** [comment]
looks good to me

**Comment by dustinryerson** [comment]
@sergiogonzalez this looks good. Would you like me to send it to BChan or do you want to do that?

Thanks again for your help with this!

**Comment by dustinryerson** [comment]
ci:stop

**Comment by dustinryerson** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @dustinryerson sure, go ahead and send the pull to Brian! Thx!

**Comment by sergiogonzalez** [comment]
ci:stop

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39418. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Thank you @sergiogonzalez!

**Pull request closed without merging**
