### PR TITLE
[Technical Support] LPS-70103 Child pages are not displayed properly in a link-to-page fi…

### PR DESCRIPTION
**Pull request by zsagia**
…eld of a structure

Hi Dustin,

I need to mention you that this issue was strange. I couldn't reproduce it at first time in ee-6.2.x but our CSE and customers could. I went to master and I could but our CSE couldn't. :)

Please go to LPS-7013 and check description and the attached images. On that images you can see that this issue is causing about that "scrollTop"'s value is a float number. That's way if we sum it to "innerHeight" it never be equals with "scrollHeight". I attached a W3.org documentation about this type change in my comment.
Just I wanted to clarify why I did this kind of solution for this issue.

I used Math.ceil() instead of Math.round() because I think scrollTop's value can be 221.2 for example.

Thanks in advance for your review and let me know if you don't understand something.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hey @zsagia,

When I tested this issue, I found that there still seems to be missing child pages. I found that even with your fix applied, child page 11 is still missing from the list. Please see my screenshot below. Is this missing child page related to the bug you're trying to fix?

missingpage

**Comment by zsagia** [comment]
Hi Dustin,

I've never seen this issue.

I'm going to check it on master.

**Comment by dustinryerson** [comment]
Thanks @zsagia I appreciate it. I just tested with Firefox v51.01 (test above was done on Chrome) and found that I could only reproduce it when creating a new web content with the new structure. When I select a page and publish the web content and then edit the web content, page 11 exists.

**Comment by zsagia** [comment]
Ohhh, :)

**Comment by dustinryerson** [comment]
@zsagia any update on this?

**Comment by zsagia** [comment]
Hi Dustin,

I tested it and I could reproduce the mentioned issue. I checked the sent request parameters and it seemed everything is correct. I continued my analyzation and I found that every 1. element will be missed from the requested items. Basically, every section will be shifted with one element. I think this is a server-side issue and it is not related with my client-side change.

The problem is that I can only reproduce it after I applied my change because without it I can see just the first 10 elements.

Please let me know if you have more questions.

Thanks,
 Zsaga

**Comment by dustinryerson** [comment]
I'll take another look at this tomorrow if I can find the time.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
