### PR TITLE
LPS-69202 New Icon Menu attribute to change the horizontal position of the overlay menu

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by alfonsocrisci** [comment]
Hello guys, I'm posting this message just to ask about how is this proceeding, as the related customer's ticket has been pending for 5 months now. Thanks a lot !

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
@rodrigopaulino @alfonsocrisci I should have this review done by tomorrow.

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/358. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
