### PR TITLE
LPS-75163 Clone the Embedded Portlet instead of setting the unused po…

### PR DESCRIPTION
**Pull request by gregory-bretall**
…rtlet variable to the clone

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
Hoping to be able to review this tomorrow.

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1176. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
