### PR TITLE
[TECHNICAL-SUPPORT] LPS-64632

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

From Alec:
>Re-submitting this change. Previously it was changed to use "your-password-has-been-sent-to-x" (x being the email address of the user) for the success message. However, since this may inadvertently reveal the user's email address if the authentication is not already by email address, I think the best alternative would be to change it in favor of a new, more generic message.

>I suppose if we do not want to make a new language key, the even more generic "The request was successful" could also be appropriate, but I think a new key makes the most sense.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
For reference: https://github.com/topolik/liferay-portal/pull/327

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Hey @Alec-Shay,

As we discussed, please separate the rename and sort done on 76576dc into separate commits. Also, please remove the change to Language_en.properties on 11c0821 as it is a generated file, and add a commit at the end that generates the language keys using a commit message like ```"LPS-64632 Language keys"```

I'll send you the steps to generate the language keys in an email.

Thanks!

**Comment by Alec-Shay** [comment]
@dustinryerson Using the steps you laid out for the language keys worked without a problem. Thanks a lot!

Sending another pull request with those changes now.

**Pull request closed without merging**
