### PR TITLE
[Technical-Support] LPS-72118

### PR DESCRIPTION
**Pull request by yuhai**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
cc @dacousalr,

Hi Dustin,

This PR extends from https://github.com/dustinryerson/liferay-portal/pull/130. Sorry to create some PR from 130-134.  I remove import version fix from journal-web, journal-content-web and portal-workflow-definition-web, it looks like I should send the related fix to https://github.com/liferay/com-liferay-journal and https://github.com/liferay/com-liferay-portal-workflow.

**Explanation:**
Based on @dacousalr guide, I revert LPS-71557 and LPS-71271, his fix will cover the kind of issue. And I have tested and it works for me.

By the way, the revert doesn't include three commit:
1.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/bae81a4d2d214bcd36d4d951ec70a223d108ad1f
2.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/a128c398e1efd67ba7095bce5e99f67f7b58f6f7
3.https://github.com/brianchandotcom/liferay-portal/pull/47839/commits/2ece88e0cceee98c506a3057482073e932009442

Because jsp doesn't use previous add linkData property. file_entry_history_action.jsp fix has been remove from LPS-71635

If you have further concerns, please kindly let me know.

Best Regards,
Hai

**Comment by yuhai** [comment]
Hi @dustinryerson 

Hope you are well.

Could you please take the priority issue?

By the  way, I just prepare the below fix in journal-web, journal-content-web and portal-workflow-definition-web.
 https://github.com/yuhai/com-liferay-journal/tree/LPS-72118
https://github.com/yuhai/com-liferay-portal-workflow/tree/LPS-72118

However, you don't have the two repositorys.

Regards,
Hai

**Comment by dustinryerson** [comment]
@yuhai I couldn't find time to get to this today but should have time tomorrow.

Thanks!

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/381. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
