### PR TITLE
LPS-67718  Children nodes get selected automatically when click on "load more results"

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Dustion

This pr should be able to solve Jon's issue.

Let me know if you have any concerns.

Thanks
John

### CODE REVIEW

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Forwarded to Jon: https://github.com/jonmak08/liferay-portal/pull/1612

**Comment by dustinryerson** [comment]
Reopening for now because my forwarded pull was closed due to some unrelated semantic versioning errors.

**Comment by dustinryerson** [comment]
ci:stop

**Comment by daledotshan** [comment]
Hey Dustin,
Just want to letting you know we have a ee customer is waiting for this fix and this issue has been opened long time, could you please treat this pull request as high priority.

**Comment by dustinryerson** [comment]
Forwarded to Jon: https://github.com/jonmak08/liferay-portal/pull/1613

**Pull request closed without merging**
