### PR TITLE
LPS-69293 Other Users can now see Locked Icon for checked-out DM files

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @NolanChan

Notes from Nolan:
>Other Users can now see Locked Icon for checked-out DM files
>
>Code originally used hasLock which determined whether the logged-in user had the lock. Instead switching to isCheckedOut as this returns whether the file is checked out regardless of user

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:retest

**Comment by NolanChan** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3593. [See changes here.](https://github.com/dustinryerson/liferay-portal/compare/c98bd7e~3...c98bd7e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
