### PR TITLE
LPS-65342

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
@ChrisKian @BryanEngler based on [this comment](https://issues.liferay.com/browse/LPP-21039?focusedCommentId=764571&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-764571), should I close this pull so that you can work on fixing the additional cases?

**Comment by ChrisKian** [comment]
Yeah that would be best.  Thanks

**Comment by dustinryerson** [comment]
Thanks @ChrisKian

**Pull request closed without merging**
